channels:
  - defaults
  - conda-forge
  - anaconda-fusion
dependencies:
  - pandas==1.0.3
  - vs2015_runtime==14.16.27012
  - freexl==1.0.5
  - msys2-conda-epoch==20160418
  - vc==14.1
  - libtiff==4.1.0
  - tiledb==1.7.0
  - m2w64-libwinpthread-git==5.0.0.4634.697f757
  - m2w64-gcc-libs-core==5.3.0
  - libblas==3.8.0
  - glib==2.58.3
  - pcre==8.44
  - cfitsio==3.470
  - python-dateutil==2.8.1
  - gettext==0.19.8.1
  - hdf4==4.2.13
  - libnetcdf==4.7.4
  - bzip2==1.0.8
  - pip==20.0.2
  - zstd==1.4.4
  - pytz==2019.3
  - six==1.14.0
  - poppler-data==0.4.9
  - gdal==3.0.4
  - libxml2==2.9.10
  - libkml==1.3.0
  - libffi==3.2.1
  - icu==64.2
  - xz==5.2.4
  - cftime==1.1.1.1
  - ca-certificates
  - m2w64-xz==5.2.2
  - libcurl==7.68.0
  - libspatialite==4.3.0a
  - boost-cpp==1.72.0
  - setuptools==46.1.3
  - m2w64-gmp==6.1.0
  - jpeg==9c
  - libwebp==1.0.2
  - postgresql==12.2
  - m2w64-gettext==0.19.7
  - libssh2==1.8.2
  - xarray
  - sqlite==3.30.1
  - curl==7.68.0
  - netcdf4==1.5.3
  - python_abi==3.7
  - wheel==0.34.2
  - libiconv==1.15
  - numpy==1.18.1
  - libpq==12.2
  - libgdal==3.0.4
  - freetype==2.10.1
  - liblapack==3.8.0
  - expat==2.2.9
  - python==3.7.6
  - m2w64-gcc-libs==5.3.0
  - libcblas==3.8.0
  - m2w64-libiconv==1.14
  - openssl
  - xerces-c==3.2.2
  - krb5==1.16.4
  - proj==6.3.1
  - intel-openmp==2020.0=166
  - openjpeg==2.3.1
  - tk==8.6.10
  - zlib==1.2.11
  - m2w64-expat==2.1.1
  - certifi
  - geos==3.8.1
  - tbb==2018.0.5
  - poppler==0.67.0
  - geotiff==1.5.1
  - hdf5==1.10.5
  - wincertstore==0.2
  - lz4-c==1.8.3
  - kealib==1.4.13
  - mkl==2020.0=166
  - m2w64-gcc-libgfortran==5.3.0
  - libpng==1.6.37
  - click
  - pytest
  - pyaml


